### ISSUE TITLE
Multiple Selectable Fields

### ISSUE THREAD

**Issue by engelbrechtd** [tabalinas/jsgrid-php#1]
What an awesome project! I am trying to create a similar scenario, but only with 3 selectable fields. Country, Province and City for example? I think specifically my problem is with my sample.js. What would an example of this file look with the 3 selectable fields?

**Comment by tabalinas** [comment]
Thank you for the feedback!
Please, check out my answer to the issue in jsgrid repo https://github.com/tabalinas/jsgrid/issues/106

**Comment by engelbrechtd** [comment]
Hi,
Thank you so much for your response. I had a look at the examples as per your post, and can not figure out how to bring it back to my PHP and MySQL. In your example.js it seems the select is part of parent function if I can call it that, and the rest of the grid is part of that function. I tried duplicating the js file, as per my gds.js, but I realized there was something wrong while debugging. I would appreciate your guidance to help me resolve this.

``` javascript
$(function() {

    $.ajax({
        type: "GET",
        url: "/gdsinfo/office/"
    }).done(function(office) {

        office.unshift({ id: "0", name: "" });

    $.ajax({
        type: "GET",
        url: "/gdsinfo/gds/"
    }).done(function(gds) {

        gds.unshift({ id: "0", name: "" });

    $.ajax({
        type: "GET",
        url: "/gdsinfo/division/"
    }).done(function(division) {

        division.unshift({ id: "0", name: "" });

    $.ajax({
        type: "GET",
        url: "/gdsinfo/brand/"
    }).done(function(brand) {

        brand.unshift({ id: "0", name: "" });

    $.ajax({
        type: "GET",
        url: "/gdsinfo/region/"
    }).done(function(region) {

        region.unshift({ id: "0", name: "" });

    $.ajax({
        type: "GET",
        url: "/gdsinfo/services/"
    }).done(function(services) {

        services.unshift({ id: "0", name: "" });

    $.ajax({
        type: "GET",
        url: "/gdsinfo/status/"
    }).done(function(status) {

        status.unshift({ id: "0", name: "" });

        $("#jsGrid").jsGrid({
            height: "70%",
            width: "100%",
            filtering: true,
            inserting: true,
            editing: true,
            sorting: true,
            paging: true,
            autoload: true,
            pageSize: 20,
            pageButtonCount: 5,
            deleteConfirm: "Do you really want to delete client?",
            controller: {
                loadData: function(filter) {
                    return $.ajax({
                        type: "GET",
                        url: "/gdsinfo/clients/",
                        data: filter
                    });
                },
                insertItem: function(item) {
                    return $.ajax({
                        type: "POST",
                        url: "/gdsinfo/clients/",
                        data: item
                    });
                },
                updateItem: function(item) {
                    return $.ajax({
                        type: "PUT",
                        url: "/gdsinfo/clients/",
                        data: item
                    });
                },
                deleteItem: function(item) {
                    return $.ajax({
                        type: "DELETE",
                        url: "/gdsinfo/clients/",
                        data: item
                    });
                }
            },
            fields: [
                { name: "cid", title: "ClientID", type: "text", width: 150 },
                { name: "identifier", title: "Identifier", type: "text", width: 150 },
                { name: "office_id", title: "Office", type: "select", width: 100, items: office, valueField: "id", textField: "office" },
                { name: "agentid", title: "AgentID", type: "text", width: 50 },
                { name: "gds_id", title: "GDS", type: "select", width: 100, items: gds, valueField: "id", textField: "gds" },
                { name: "gdsinfo", title: "GDS Info", type: "text", width: 150 },
                { name: "username", title: "Username", type: "text", width: 150 },
                { name: "division_id", title: "Division", type: "select", width: 100, items: division, valueField: "id", textField: "division" },
                { name: "brand_id", title: "Brand", type: "select", width: 100, items: brand, valueField: "id", textField: "brand" },
                { name: "region_id", title: "Division", type: "select", width: 50, items: region, valueField: "id", textField: "region" },
                { name: "air_device", title: "AIR Device", type: "text", width: 50 },
                { name: "print_device", title: "Printer Device", type: "text", width: 50 },
                { name: "tkt_device", title: "Ticket Device", type: "text", width: 50 },
                { name: "services_id", title: "Services", type: "select", width: 50, items: services, valueField: "id", textField: "service" },
                { name: "status_id", title: "Status", type: "select", width: 50, items: status, valueField: "id", textField: "status" },
                { type: "control" }
            ]
        });

    });


});

});
```

**Comment by tabalinas** [comment]
In your case the simplest way is to use `$.when`
https://api.jquery.com/jquery.when/

you can do the following:

``` js
var promise1 = $.ajax({ first select ajax });
var promise2 = $.ajax({ second select ajax });
var promiseN = $.ajax({ N-th select ajax });

$.when(promise1, promise2, promiseN).done(function(items1, item2, itemsN) {
    // initialize js-grid having all the dropdown items
});
```

**Comment by engelbrechtd** [comment]
thank you for this. Im getting there, slowly, but surely. Im not getting
any errors while loading the page, but my selects are empty.

my .js:

var seloffice = $.ajax({ type: "GET", url: "/gdsinfo/office/" });
var selgds = $.ajax({ type: "GET", url: "/gdsinfo/gds/" });
var seldivision = $.ajax({ type: "GET", url: "/gdsinfo/division/" });
var selbrand = $.ajax({ type: "GET", url: "/gdsinfo/brand/" });
var selregion = $.ajax({ type: "GET", url: "/gdsinfo/region/" });
var selservices = $.ajax({ type: "GET", url: "/gdsinfo/services/" });
var selstatus = $.ajax({ type: "GET", url: "/gdsinfo/status/" });
var selcustodian = $.ajax({ type: "GET", url: "/gdsinfo/custodian/" });

$.when(seloffice, selgds, seldivision, selbrand, selregion, selservices,
selstatus, selcustodian).done(function( office, gds, division, brand,
region, services, status, custodian ) {

```
office.unshift({ id: "0", name: "" });
gds.unshift({ id: "0", name: "" });
division.unshift({ id: "0", name: "" });
brand.unshift({ id: "0", name: "" });
region.unshift({ id: "0", name: "" });
services.unshift({ id: "0", name: "" });
status.unshift({ id: "0", name: "" });
custodian.unshift({ id: "0", name: "" });

    $("#jsGrid").jsGrid({
        height: "95%",
        width: "100%",
        filtering: true,
        inserting: true,
        editing: true,
        sorting: true,
        paging: true,
        autoload: true,
        pageSize: 20,
        pageButtonCount: 5,
        deleteConfirm: "Do you really want to delete this client?",
        controller: {
            loadData: function(filter) {
                return $.ajax({
                    type: "GET",
                    url: "/gdsinfo/clients/",
                    data: filter
                });
            },
            insertItem: function(item) {
                return $.ajax({
                    type: "POST",
                    url: "/gdsinfo/clients/",
                    data: item
                });
            },
            updateItem: function(item) {
                return $.ajax({
                    type: "PUT",
                    url: "/gdsinfo/clients/",
                    data: item
                });
            },
            deleteItem: function(item) {
                return $.ajax({
                    type: "DELETE",
                    url: "/gdsinfo/clients/",
                    data: item
                });
            }
        },
        fields: [
            { name: "cid", title: "ClientID", type: "text", width: 100
```

},
                { name: "identifier", title: "Identifier", type: "text",
width: 100 },
                { name: "office_id", title: "Office", type: "select",
width: 80, items: office, valueField: "id", textField: "office" },
                { name: "agentid", title: "AgentID", type: "text", width:
80 },
                { name: "gds_id", title: "GDS", type: "select", width: 80,
items: gds, valueField: "id", textField: "name" },
                { name: "gdsinfo", title: "GDS Info", type: "text", width:
100 },
                { name: "username", title: "Username", type: "text", width:
100 },
                { name: "division_id", title: "Division", type: "select",
width: 100, items: division, valueField: "id", textField: "name" },
                { name: "brand_id", title: "Brand", type: "select", width:
100, items: brand, valueField: "id", textField: "name" },
                { name: "region_id", title: "Region", type: "select",
width: 100, items: region, valueField: "id", textField: "name" },
                { name: "air_device", title: "AIR", type: "text", width: 80
},
                { name: "print_device", title: "PRN", type: "text", width:
80 },
                { name: "tkt_device", title: "TKT", type: "text", width: 80
},
                { name: "services_id", title: "Services", type: "select",
width: 100, items: services, valueField: "id", textField: "name" },
                { name: "status_id", title: "Status", type: "select",
width: 100, items: status, valueField: "id", textField: "name" },
                { name: "custodian_id", title: "Custodian", type: "select",
width: 100, items: custodian, valueField: "id", textField: "name" },
                { type: "control" }
            ]
        });

```
});
```

[image: Inline image 1]

But when I go to /gdsinfo/office/, I get the JSON results for the dropdown.

On Tue, Sep 29, 2015 at 12:37 AM, Artem Tabalin notifications@github.com
wrote:

> In your case the simplest way is to use $.when
> https://api.jquery.com/jquery.when/
> 
> you can do the following:
> 
> var promise1 = $.ajax({ first select ajax });var promise2 = $.ajax({ second select ajax });var promiseN = $.ajax({ N-th select ajax });
> 
> $.when(promise1, promise2, promiseN).done(function(items1, item2, itemsN) {
>     // initialize js-grid having all the dropdown items
> });
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tabalinas/jsgrid-php/issues/1#issuecomment-143893459.

## 

_darrell engelbrecht_ _//_ angelbright _//_ _e_ darrell@angelbright.co.za

## _//_ _w_ www.angelbright.co.za _//_ johannesburg _//_ south africa

reach high, for stars lie hidden in your soul. dream deep, for every dream
precedes the goal _-pamela vaull_

**Comment by tabalinas** [comment]
Your code looks good. Try to `console.log` the results like `office` and `gds`. Ensure that you get appropriate arrays of items. Maybe you need to make `JSON.parse` or specify `contentType: 'application/json'` for your ajax requests.

**Comment by engelbrechtd** [comment]
Okay, this is way over my pay grade!! :-) I understand in concept what the
console.log does, not sure how to apply it, or even more specifically, how
to apply it only for those 2 elements?

I will do some research on the JSON.parse and 'contentType'
'application/json' options. Thank you again.

On Thu, Oct 1, 2015 at 12:38 AM, Artem Tabalin notifications@github.com
wrote:

> Your code looks good. Try to console.log the results like office and gds.
> Ensure that you got appropriate arrays of items. Maybe you need to make
> JSON.parse or specify contentType: 'application/json' for your ajax
> requests.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tabalinas/jsgrid-php/issues/1#issuecomment-144565239.

## 

_darrell engelbrecht_ _//_ angelbright _//_ _e_ darrell@angelbright.co.za

## _//_ _w_ www.angelbright.co.za _//_ johannesburg _//_ south africa

reach high, for stars lie hidden in your soul. dream deep, for every dream
precedes the goal _-pamela vaull_

**Comment by wichy5** [comment]
Hi engelbrechtd,
Did you fix it? I have the same problem (selects are empty) and I see the results in console.log and it's ok, and I specify the contentType: 'application/json' on ajax requests.
I don't know how to fix it...
Thanks

**Comment by tabalinas** [comment]
If you see data printed with console.log then it should work just like with static data.
Maybe something wrong in jsGrid configuration. Have you tried to make it work with static array for select field?

**Comment by wichy5** [comment]
Hi tabalinas,
I fix it but not with $.when, I use:

$.ajax({
        type: "GET",
        url: "/categories/"
    }).done(function(category) {
            category.unshift({ id: 0, name: "" });

```
        $.ajax({
              type: "GET",
              url: "/products/"
        }).done(function(product) {

             product.unshift({ id: 0, name: "" });
        ....
```

And it works fine!!!  :)

Thanks

**Comment by tabalinas** [comment]
Glad to hear that!

**Comment by AbderrazakEldouqe** [comment]
I have  two select (selects are empty) and I see the results in console.log and it's ok, and I specify the contentType: 'application/json' on ajax requests.
I don't know how to fix it??
Thanks

**Comment by lucks** [comment]
You can use :
`
 let d1 = $.ajax({});
let d2 = $.ajax({});
 $.when(d1,d2).done(function(r1,r2){
 $('#jsGridTable').jsGrid({
  fields: [
                {
                    type: "select",
                    items: r1[0]
                    },
 {
                    type: "select",
                    items: r2[0]
                    }
});
});`
