### ISSUE TITLE
rendering issue with two select boxes

### ISSUE THREAD

**Issue by hk298** [tabalinas/jsgrid-php#10]
My code is based on the php sample code and, in general, I am very happy with it. I have one table with a single select box which is working fine. Now I also need a table with two select boxes and several text and number fields. A code snippet for this is below. This one loads properly, and inserting and filtering work fine.

```
$(function() {

  $.ajax({
    type: "GET",
    url: "/grid/table1.php"
  }).done(function(array1) {

    array1.unshift({ id: "0", name: "" });

    $.ajax({
      type: "GET",
      url: "/grid/table2.php"
    }).done(function(array2) {

      array2.unshift({ id: "0", name: "" });

      $("#jsGrid").jsGrid({
        height: "90%",
        width: "100%",
        autoload: false,
```

However, when I update a field in a row, the two select boxes in that row will display nothing. It does not matter which of the fields I update. The database is updated properly and sorting still works correctly. When I edit the row again, the values are shown again. Accept or cancel the edit, and the fields are blank again. When I then filter on a a column with a select box, the value is shown again. Remove the filter, and the values are still shown until I edit again.

My current workaround is the following:

```
        onItemUpdated: function(args) {
          $("#jsGridCallDefinitions").jsGrid("loadData");
        },
```

Is that really needed? Seems odd since the example with one select box works just fine. I also tried "render" and "refresh" without success. The fields are displayed properly only after I call "loadData" again.

**Comment by tabalinas** [comment]
No, this should not be necessary.
Do you have your example available in public, or maybe you provide a demo reproducing the issue (in jsfiddle or any other way)?

**Comment by hk298** [comment]
Since I included an _onItemUpdated_ event handler in the table that has only a single select box I have the same problem there as well.

I will copy this project to a machine with a public IP address and let you know via email.

**Comment by hk298** [comment]
The issue was three different data types for the "id" field. In the `array.unshift` command it was a string, in table1 it was 'serial' which turned into 'int' and in table2 I used 'bigint'.
