### ISSUE TITLE
Data Not displaying

### ISSUE THREAD

**Issue by vartanian** [tabalinas/jsgrid-php#13]
Hi Tabalinas,
Hoping you can help. We seem to have gotten the data to return, but wont display on the screen, even though we see the json. We tried Insert and it seems to work, however the Select \* we have returning is not showing. We removed the filter param and data: filter, and regardless with it in or out it wont work. There is no error showing up anywhere front or back... Any tips?

``` js
        controller: {
            loadData: function(filter) {
                return $.ajax({
                    type: "GET",
                    url: blacklist,
                    data: filter
                });
            },
```

**Comment by tabalinas** [comment]
There could be many reasons:
- `autoload` is `false` so the grid is not loading by default
- wrong definition of grid fields (check if you have errors on console)
- wrong format of data coming from backend (check in DevTools the format of data coming from backend)

**Comment by tabalinas** [comment]
Close due to inactivity
