### ISSUE TITLE
json_encode

### ISSUE THREAD

**Issue by Ricardo-Herrero** [tabalinas/jsgrid-php#3]
From /countries/index.php I just receive [{"id":"1","name":"espana"},{"id":"2","name":"francia"}]. What about jsgrid functions? What I am doing wrong? Thanks for your help.

**Comment by tabalinas** [comment]
Not sure I understand the issue. Could you describe it in more details?
What jsgrid function? What result do you get, and what do you expect?

**Comment by Ricardo-Herrero** [comment]
I have had problems with sample.js paths as I´m using Fedora, and I just could see the result for clients.php, without jsgrid table formatting. 
I have achieved that now. However, I have a doubt, maybe you can solve me. What do I have to do to call two foreign key tables, instead of just one like countries with clients in your example, I need to do the same, something like continents, countries, and clients. Thanks in advance, great job!

**Comment by tabalinas** [comment]
See my comment to another issue https://github.com/tabalinas/jsgrid-php/issues/1#issuecomment-143893459
