### ISSUE TITLE
php connection ok but no table displayed on html page

### ISSUE THREAD

**Issue by damiendevienne** [tabalinas/jsgrid-php#4]
Hello, 
Thanks for this great project. I am trying to use this jsgrid-php, but cannot make it to work, and I don't understand what I am missing.  
I changed the db configuration to connect to my mysql database, and this works: when I go to `localhost/clients` for example, I am getting the correct json of my table on screen. 
However, when loading `localhost/index.html`, I get the title of the page (JSGrid and PHP Sample), but nothing more. In the div in which the table is supposed to appear, nothing is shown. 
Is there some configuration that I am missing? Thanks a lot. 

Note that I have put all files in /var/www/html, and I only modified the `db/config.php` file.

**Comment by damiendevienne** [comment]
UPDATE: I think that I solved it without knowing why... Sorry...

**Comment by tabalinas** [comment]
Glad that you figured it out.
