### ISSUE TITLE
Predefined Values

### ISSUE THREAD

**Issue by dipiana** [tabalinas/jsgrid-php#6]
Is it possible to set predefined values for fields? For example I would like to to have certain checkboxes check by default, as soon as I create a new DB-Entry.

Thanks a lot!

**Comment by tabalinas** [comment]
What's about setting default values in `controller.insertItem` before sending data to the server?
Or if you wish to set default value in the inserting control then you can do something like (example for text field):

``` js
insertTemplate: function() {
    var $insertControl = jsGrid.fields.text.prototype.insertTemplate.call(this);
    return $insertControl.val("my-default-value");
}
```
