### ISSUE TITLE
Controllers Security

### ISSUE THREAD

**Issue by tpfilipe** [tabalinas/jsgrid-php#7]
Hello.

I am doing a web application that use javascript, html and php. I'm using this example to load the data from database in jsGrid. I'm really newbie with PHP, so I want to know if its possible to secure the information that goes to the client side to the server side by json.

Example:
When I go to:
localhost/controllers/StopController
Browser returns: 
[{"Stop":"PID Track1","Zone":"1001001","Status":false},{"Stop":"Byparken","Zone":"1001000","Status":false},{"Stop":"PID Terminal","Zone":"1001002","Status":false}]

What if the application client knows that url and stole all the private information? Is any way to controll this? Maybe with PHP session, I don't know...

This is my final work for university and I don't wanna to implement something without a good security :/

Sorry for my bad english,
Best regards

**Comment by tabalinas** [comment]
I'm not sure your question relates in anyway to js-grid sample project.
I advise you to search for answers to your questions in the inet, e.g. checkout this nice manual https://www.sitepoint.com/best-practices-rest-api-scratch-introduction/
