### ISSUE TITLE
Output format when pageLoading = true

### ISSUE THREAD

**Issue by thaarok** [tabalinas/jsgrid-php#8]
Service **GET /clients** returns list of rows, but when **pageLoading** is set to **true**, output of this service should be in fomat:

```
{
    data: [items],
    itemsCount: amountOfItems
}
```

As mentioned at https://github.com/tabalinas/jsgrid/issues/35

When I followed current example, loading stopped in "Please, wait..." phase.

**Comment by tabalinas** [comment]
The problem most probably is in the config of the grid. Or in the format of data coming from the server. Ensure that `loadData` is called and you successfully getting results from the server in the correct format (also check the browser console, maybe there is an error message).

**Comment by thaarok** [comment]
As I wrote, problem is in data coming from server - this example (jsgrid-php) returns list of rows, not enclosed in "data" attribute:
https://github.com/tabalinas/jsgrid-php/blob/master/clients/index.php#L11
When I rewrite this, everything works - but sample in this repository should be fixed.

**Comment by tabalinas** [comment]
For this sample project `pageLoading` is disabled, all the data loaded at once. What you describe is applied only for `pageLoading: true` scenario.  I don't see the problem.

**Comment by thaarok** [comment]
Sorry, I have accidentaly mixed two samples. Closing.
