### ISSUE TITLE
handling SQL failures

### ISSUE THREAD

**Issue by hk298** [tabalinas/jsgrid-php#9]
I'm wondering how to handle failures from the SQL server. Let's look at inserts as an example. The documentation for the controller says that insertItem(item) "should return insertedItem or jQuery promise that will be resolved with insertedItem. If no item is returned, inserting item will be used as inserted item." I'm having a little issue with the last part. I think if nothing is returned, the grid should pop up an error, just using the "inserting item" will give the user the false impression that the insert succeeded. The current PHP sample code actually throws an error because the getById will fail (lastInsertId is null) and then it returns a JSON record where all fields are set to null. The grid then adds a new line where all fields are empty. This is a little better, but still not great.

When doing updates, I have the same problem. An update that failed is not visible to the user until the grid is refreshed because "If no item is returned, updating item will be used as updated item." Again, I think it would probably better if "no item returned" is treated as an error.

Besides that, I quite like jsGrid and I'm happy you provided a working example of the PHP backend. Thanks. :-)

**Comment by hk298** [comment]
A validation function that prevents users from entering bad values in the first place would also solve the problem. However, that seems to require a synchronous call, for example like this:

```
  fields: [
    { name: "name", title: "Name", type: "text", width: 150,
      validate: [
        "required",
        { validator: function(value, item) {
            ok = false;
            $.ajax({ 
              async: false,
              type: "GET",
              url: "/grid/dbCheckName.php",
              data: { name: value },
              success: function(result){
                ok = result.count == 0;
              }
              });
              return ok;
            },
          message: "Name needs to be unique."
        }
      ]
    },
```

The php function basically does a `SELECT count(*) FROM table WHERE name = 'name'`
Ok, now flame me for using `async: false` or suggest something better.

**Comment by tabalinas** [comment]
Thank you for the feedback. What I don't understand is why you cannot return a proper error status from backend in the case of error? Then just handle `onError` and show particular alert to the user.

**Comment by hk298** [comment]
Thanks for the reply. I'm new to this and didn't know any better. Now I am doing the checks on the backend and have it set custom headers such as
`header('HTTP/1.1 500 Name is not unique');`
in case something is not right. Or is there a better way for the backend to communicate meaningful error messages back to the frontend?

**Comment by tabalinas** [comment]
Yes, this should work, just provide error info in some way, so that front-end could properly explain the reason of the problem to the user.
This could be 409 as it's stated here http://stackoverflow.com/questions/3290182/rest-http-status-codes-for-failed-validation-or-invalid-duplicate
